//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIEB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Expense
    {
        public int ExpenseID { get; set; }
        public int PersonID { get; set; }
        public int ExpenseType { get; set; }
        [Display(Name = "Ödeme Türü")]
        public string PaymentType { get; set; }
        [Display(Name = "Miktar")]
        public decimal Amount { get; set; }
        [Display(Name = "Tarih")]
        public System.DateTime Date { get; set; }
        [Display(Name = "Bankalarým")]
        public Nullable<int> BankID { get; set; }
        [Display(Name = "Kredi Kartlarým")]
        public Nullable<int> CreditID { get; set; }
        [Display(Name = "Taksit Bilgileri")]
        public string InstallmentInfo { get; set; }
        [Display(Name = "Ödeme Bilgisi")]
        public string PaymentInfo { get; set; }
        [Display(Name = "Diðer Harcama Türü")]
        public string Explanation { get; set; }
    
        public virtual BankCartType BankCartType { get; set; }
        public virtual CreditCartType CreditCartType { get; set; }
        public virtual ExpenseType ExpenseType1 { get; set; }
        public virtual Persons Persons { get; set; }
    }
}
